import { AppContextProvider } from "@/contexts/AppContext";
import { Geist, Geist_Mono, Manrope, Oswald } from "next/font/google";
import "./globals.css";

import Nav from '@/components/Nav'
import Footer from '@/components/Footer';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  variable: '--font-manrope',
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
});

const oswald = Oswald({
  subsets: ['latin'],
  weight: ['200', '300', '400', '500', '600', '700'],
  variable: '--font-oswald',
});

export const metadata = {
  title: "Pixel Cinema",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className={`bg-[#08103B] min-h-screen text-white ${manrope.variable} ${oswald.variable}`}>
        <AppContextProvider>
            <Nav />
              {children}
            <Footer />
        </AppContextProvider>
      </body>
    </html>
  );
}
